name: build

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '1 1 * * 0'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Fetch files
        run: |
          sudo apt-get -q update
          sudo apt-get install dos2unix rename lynx
          ./CI/build.sh
